// <auto-generated />
using System;
using Lager.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lager.Migrations
{
    [DbContext(typeof(LagerDbContext))]
    [Migration("20260924095939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Lager.Models.AppleInput", b =>
                {
                    b.Property<int>("AppleInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kilograms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AppleInputId");

                    b.HasIndex("BatchId");

                    b.ToTable("AppleInputs");
                });

            modelBuilder.Entity("Lager.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentTankId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentVolumeLiters")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFlaggedBad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("CurrentTankId");

                    b.HasIndex("ProductId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Lager.Models.BatchAddition", b =>
                {
                    b.Property<int>("BatchAdditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BatchVolumeLiters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BatchAdditionId");

                    b.HasIndex("BatchId");

                    b.HasIndex("SupplyId");

                    b.ToTable("BatchAdditions");
                });

            modelBuilder.Entity("Lager.Models.BatchParent", b =>
                {
                    b.Property<int>("ChildBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Liters")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildBatchId", "ParentBatchId");

                    b.HasIndex("ParentBatchId");

                    b.ToTable("BatchParents");
                });

            modelBuilder.Entity("Lager.Models.Bottling", b =>
                {
                    b.Property<int>("BottlingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BestBefore")
                        .HasColumnType("TEXT");

                    b.Property<int>("BottleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BottledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BottlingId");

                    b.HasIndex("BatchId");

                    b.HasIndex("LotNumber")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("Bottlings");
                });

            modelBuilder.Entity("Lager.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("MeasurementId");

                    b.HasIndex("BatchId");

                    b.HasIndex("TankId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Lager.Models.Pasteurization", b =>
                {
                    b.Property<int>("PasteurizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CalculatedPu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequiredPu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PasteurizationId");

                    b.HasIndex("BatchId");

                    b.ToTable("Pasteurizations");
                });

            modelBuilder.Entity("Lager.Models.PasteurizationReading", b =>
                {
                    b.Property<int>("PasteurizationReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PasteurizationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("PasteurizationReadingId");

                    b.HasIndex("PasteurizationId");

                    b.ToTable("PasteurizationReadings");
                });

            modelBuilder.Entity("Lager.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Lager.Models.RecipeLine", b =>
                {
                    b.Property<int>("RecipeLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPerLiter")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplyId");

                    b.ToTable("RecipeLines");
                });

            modelBuilder.Entity("Lager.Models.StorageLocation", b =>
                {
                    b.Property<int>("StorageLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WidthMeters")
                        .HasColumnType("TEXT");

                    b.HasKey("StorageLocationId");

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("Lager.Models.Supply", b =>
                {
                    b.Property<int>("SupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityInStock")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shelf")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplyId");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Lager.Models.Tank", b =>
                {
                    b.Property<int>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacityLiters")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiameterMeters")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PositionY")
                        .HasColumnType("TEXT");

                    b.Property<string>("RfidTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TankId");

                    b.HasIndex("RfidTag")
                        .IsUnique();

                    b.HasIndex("StorageLocationId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("Lager.Models.TankTransfer", b =>
                {
                    b.Property<int>("TankTransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromTankId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Liters")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToTankId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TankTransferId");

                    b.HasIndex("BatchId");

                    b.HasIndex("FromTankId");

                    b.HasIndex("ToTankId");

                    b.ToTable("TankTransfers");
                });

            modelBuilder.Entity("Lager.Models.TastingNote", b =>
                {
                    b.Property<int>("TastingNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("TastingNoteId");

                    b.HasIndex("BatchId");

                    b.ToTable("TastingNotes");
                });

            modelBuilder.Entity("Lager.Models.AppleInput", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("AppleInputs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Lager.Models.Batch", b =>
                {
                    b.HasOne("Lager.Models.Tank", "CurrentTank")
                        .WithMany("CurrentBatches")
                        .HasForeignKey("CurrentTankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lager.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("CurrentTank");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lager.Models.BatchAddition", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("Additions")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lager.Models.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Lager.Models.BatchParent", b =>
                {
                    b.HasOne("Lager.Models.Batch", "ChildBatch")
                        .WithMany("Parents")
                        .HasForeignKey("ChildBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lager.Models.Batch", "ParentBatch")
                        .WithMany("Children")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildBatch");

                    b.Navigation("ParentBatch");
                });

            modelBuilder.Entity("Lager.Models.Bottling", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("Bottlings")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lager.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lager.Models.Measurement", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("Measurements")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lager.Models.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId");

                    b.Navigation("Batch");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("Lager.Models.Pasteurization", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("Pasteurizations")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Lager.Models.PasteurizationReading", b =>
                {
                    b.HasOne("Lager.Models.Pasteurization", "Pasteurization")
                        .WithMany("Readings")
                        .HasForeignKey("PasteurizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasteurization");
                });

            modelBuilder.Entity("Lager.Models.RecipeLine", b =>
                {
                    b.HasOne("Lager.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lager.Models.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Lager.Models.Supply", b =>
                {
                    b.HasOne("Lager.Models.StorageLocation", "StorageLocation")
                        .WithMany("Supplies")
                        .HasForeignKey("StorageLocationId");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Lager.Models.Tank", b =>
                {
                    b.HasOne("Lager.Models.StorageLocation", "StorageLocation")
                        .WithMany("Tanks")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Lager.Models.TankTransfer", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("Transfers")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lager.Models.Tank", "FromTank")
                        .WithMany()
                        .HasForeignKey("FromTankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lager.Models.Tank", "ToTank")
                        .WithMany()
                        .HasForeignKey("ToTankId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("FromTank");

                    b.Navigation("ToTank");
                });

            modelBuilder.Entity("Lager.Models.TastingNote", b =>
                {
                    b.HasOne("Lager.Models.Batch", "Batch")
                        .WithMany("TastingNotes")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Lager.Models.Batch", b =>
                {
                    b.Navigation("Additions");

                    b.Navigation("AppleInputs");

                    b.Navigation("Bottlings");

                    b.Navigation("Children");

                    b.Navigation("Measurements");

                    b.Navigation("Parents");

                    b.Navigation("Pasteurizations");

                    b.Navigation("TastingNotes");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("Lager.Models.Pasteurization", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Lager.Models.StorageLocation", b =>
                {
                    b.Navigation("Supplies");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("Lager.Models.Tank", b =>
                {
                    b.Navigation("CurrentBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
